version: '3.8'

services:
  app:
    container_name: desafio-oi-dev
    image: desafio-oi-image-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    environment:
      - BROWSER=none
